site/routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Http\FileHelpers;
use Illuminate\Filesystem\Filesystem;

/// ----- AUTH ROUTES -----
Route::get('login/', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('login/success', 'Auth\LoginController@login')->name('login.success');

/// ----- HOME ROUTES -----
Route::redirect('/', 'login');
Route::get('/home', 'HomeController@show')->name('home');
/*      ->middleware('lucs.login')->name('home'); */
Route::redirect('intrahome', 'http://intranet.csc.liv.ac.uk' )->name('intrahome');

/// ----- USER ROUTES -----
Route::resource('user', 'UserController', ['only' => [
    'index'
]]);

/// ----- STUDENT ROUTES -----
Route::resource('student', 'StudentController', ['except' => [
    'destroy'
]])->middleware('lucs.login');
Route::post('student/bulk', 'StudentController@storeBulk')->name('student.bulk.store');
Route::get('student/bulk/create', 'StudentController@createBulk')->name('student.bulk.create');

/// ----- PHD PLAN ROUTES -----
Route::resource('plan/approval', 'PhdPlanApprovalController', ['only' => [
    'create', 'store'
]]);

/// ----- WORKFLOW ROUTES -----
Route::get('workflow/create/{student}', 'WorkflowController@create')->name('workflow.create');
Route::resource('workflow', 'WorkflowController', ['only' => [
    'store', 'update', 'destroy'
]]);

/// ----- WORKFLOW TYPE ROUTES -----
Route::resource('workflow_type', 'WorkflowTypeController', [ 'only' => [
    'show'
]]);

/// ----- FEEDBACK ROUTES -----
Route::name('feedback.')->group(function() {
    Route::get('{userId}/feedback', 'FeedbackController@create')->name('enter');
    Route::get('{feedback}/{studentId}/feedback/', 'FeedbackController@show')->name('view');
    Route::post('feedback/upload', 'FeedbackController@store')->name('upload');
    Route::get('feedback/committee/comments/create/{feedback}', 'DataForProgressCommitteeController@create')->name('committee_data.create');
    Route::post('feedback/committee/comments/store', 'DataForProgressCommitteeController@store')->name('committee_data.store');
    Route::get('feedback/committee/comments/show/{data}', 'DataForProgressCommitteeController@show')->name('committee_data.show');
});

/// ----- DOCUMENT ROUTES -----
Route::resource('document', 'DocumentController', ['only' => [
    'index', 'store', 'show'
]]);

/// ----- SUPERVISOR ROUTES -----
Route::name('supervisor.')->group(function() {
    Route::delete('supervisor/{staff}/{student}', 'SupervisorController@destroy')->name('destroy');
    Route::post('supervisor/', 'SupervisorController@store')->name('store');
});

/// ----- IPAP ROUTES -----
Route::name('ipap.')->group(function() {
    Route::delete('ipap/{staff}/{student}', 'IPAPController@destroy')->name('destroy');
    Route::post('ipap/', 'IPAPController@store')->name('store');
});

Route::resource('meeting', 'IPAPMeetingController', ['only' => [
    'store', 'edit', 'update'
]]);

/// ----- STAFF VIEW ROUTES -----
Route::name('staff_views.')->group(function() {
    Route::get('students/ipap/show', 'StaffViewsController@showIpapStudentsView')->name('students.ipap.show');
    Route::get('students/supervising/show', 'StaffViewsController@showSupervisingStudentsView')->name('students.supervising.show');
});

/// ----- MASQUERADE ROUTES -----
Route::get('masquerade/{username}', 'MasqueradeController@masqueradeAs')->name('masquerade');
Route::get('stop/masquerade', 'MasqueradeController@stopMasquerade')->name('masquerade.stop');

/// ----- EXEMPTION ROUTES -----
Route::get('exemption/{student_username}', 'ExemptionController@request')->name('exemption.request');
Route::get('exemption/grant/{student_username}', 'ExemptionController@grant')->name('exemption.grant');

?>

site/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Student;
use App\Staff;
use App\IPAP;
use App\Supervisor;
use App\LUCS_User;

/* use Illuminate\Foundation\Bus\DispatchesJobs;
 * use Illuminate\Routing\Controller as BaseController;
 * use Illuminate\Foundation\Validation\ValidatesRequests;
 * use Illuminate\Foundation\Auth\Access\AuthorizesRequests;*/

class HomeController extends Controller
{
    public function show(Request $request)
    {
        $user = auth()->user();

        if ($user->isStudent()) {
            return view('home.student', ['user' => $user]);
        }

        return view ('home.staff');
    }

    private function render_ipap($user)
    {
        // $ipap = IPAP::where('staff_username', $user->username)->first();
        // $students = $ipap->students()->get();
        $students = $user->staff->students()->get();
        
        return view('home.staff', ['students' => $students]);
    }
    
    private function render_supervisor($user)
    {
        // $supervisor = Supervisor::where(
        //     'staff_username',
        //     $user->username
        // )->first();

        // $students = $supervisor->students()->get();
        $students = $user->staff->students()->get();

        return view('home.staff', ['students' => $students]);
    }
}

?>

site/resources/views/home/admin.blade.php
@extends('home.index')

@section('home.content')
    <div class="row-sm mt-3">
        <h4 class="mb-3">
            <span style="text-align:left;">
                All Students
            </span>
            <span style="float:right;">
                <a class="btn btn-info" href="{{ URL::route('student.create') }}">New Student</a>
            </span>
        </h4>
        {{-- $students->links() --}}
        @component('components.student-list', ['students' => $students])
        @endcomponent
        {{-- $students->links() --}}
    </div>
@endsection

site/resources/views/home/index.blade.php
@extends('layouts.app')

@section('title')
    Home - {{ auth()->user()->firstnames }} {{ auth()->user()->surname }}
@endsection

@section('content')
    <div class="row-sm mt-3">
        <div class="col-sm">
            @component('components.welcome-msg')
                @slot('msg')
                    Welcome {{ auth()->user()->firstnames }} {{ auth()->user()->surname }}
                @endslot
            @endcomponent
        </div>
    </div>

    <div class="row-sm mt-3">
        <div class="col">
            @component('components.alert')
            @slot('print_errors')
            @foreach ($errors->all() as $error)
                File upload failed: {{ $error }}
            @endforeach
            @endslot
            @endcomponent
        </div>
    </div>

    <div class="row-sm">
        <div class="col">
            @yield('home.content')
        </div>
    </div>
@endsection

site/resources/views/home/progress_committee.blade.php
@extends('home.index')

@section('home.content')
    <div class="row-sm mt-3">
        <h4 class="mb-3">
            <span style="text-align:left;">
                Students Requiring Attention
            </span>
        </h4>
        {{-- $workflows->links() --}}
        <div class="mt-3 mb-3">
            @foreach ($workflows as $workflow)
                {{ $workflow->student->lucsUser->firstnames ?? $workflow->student->username }} {{ $workflow->student->lucsUser->surname ?? '' }}
                @component('components.document', ['doc' => $workflow->student->documents->where('workflow_type_id', $workflow->type->id)->first()])
                @endcomponent
            @endforeach
        </div>
        {{-- $workflows->links() --}}
    </div>
@endsection

site/resources/views/home/staff.blade.php
@extends('home.index')

@section('home.content')
    @if(auth()->user()->isIpap())
        <div class="row-sm">
            <h4>Outstanding Feedback</h4>
            @forelse(auth()->user()->staff->documentsNeedingAttention() as $document)
                <h5>{{ $document->student->lucsUser->firstnames ?? $document->student->username }} {{ $document->student->lucsUser->surname ?? '' }}</h5>
                @component('components.document', ['doc' => $document])
                @endcomponent
            @empty
                <div class="card">
                    <div class="card-body">
                        <p>You have no outstanding feedback</p>    
                    </div>
                </div>
            @endforelse
        </div>
        <div class="row-sm mt-3">
            <h4>My IPAP Students</h4>
            @component('components.student-list', ['students' => auth()->user()->staff->ipapStudents, 'id' => 1])
            @endcomponent
        </div>
    @endif

    @if(auth()->user()->isSupervisor())
        <div class="row-sm mt-3">
            <h4>Currently Supervising Students</h4>
            @component('components.student-list', ['students' => auth()->user()->staff->supervisingStudents, 'id' => 2])
            @endcomponent
        </div>
    @endif

    @if(auth()->user()->isAdmin())
        <h4 class="mb-3">
            <span style="text-align:left;">
                All Students
            </span>
            <span style="float:right;">
                <a class="btn btn-info" href="{{ URL::route('student.create') }}">New Student</a>
            </span>
        </h4>
        @component('components.student-list', ['students' => \App\Student::all(), 'id' => 3])
        @endcomponent
    @endif
@endsection

site/resources/views/home/student.blade.php
@extends('home.index')

@section('home.content')
    <div class="row-sm">
        <h4>Submitted Documents</h4>
        @forelse(auth()->user()->student->documents as $document)
            @component('components.document', ['doc' => $document])
            @endcomponent
        @empty
            <div class="card mt-3">
                <div class="card-body">
                    <p class="card-title">No documents have been submitted yet</p>
                </div>
            </div>
        @endforelse
    </div>
    
    @unless($user->student->workflows->count() == 0)
        <div class="row-sm mt-3 mb-3">
            @include('components.document-upload', ['workflows' => $user->student->workflows])
        </div>
    @endunless
@endsection