site/routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Http\FileHelpers;
use Illuminate\Filesystem\Filesystem;

/// ----- AUTH ROUTES -----
Route::get('login/', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('login/success', 'Auth\LoginController@login')->name('login.success');

/// ----- HOME ROUTES -----
Route::redirect('/', 'login');
Route::get('/home', 'HomeController@show')->name('home');
/*      ->middleware('lucs.login')->name('home'); */
Route::redirect('intrahome', 'http://intranet.csc.liv.ac.uk' )->name('intrahome');

/// ----- USER ROUTES -----
Route::resource('user', 'UserController', ['only' => [
    'index'
]]);

/// ----- STUDENT ROUTES -----
Route::resource('student', 'StudentController', ['except' => [
    'destroy'
]])->middleware('lucs.login');
Route::post('student/bulk', 'StudentController@storeBulk')->name('student.bulk.store');
Route::get('student/bulk/create', 'StudentController@createBulk')->name('student.bulk.create');

/// ----- PHD PLAN ROUTES -----
Route::resource('plan/approval', 'PhdPlanApprovalController', ['only' => [
    'create', 'store'
]]);

/// ----- WORKFLOW ROUTES -----
Route::get('workflow/create/{student}', 'WorkflowController@create')->name('workflow.create');
Route::resource('workflow', 'WorkflowController', ['only' => [
    'store', 'update', 'destroy'
]]);

/// ----- WORKFLOW TYPE ROUTES -----
Route::resource('workflow_type', 'WorkflowTypeController', [ 'only' => [
    'show'
]]);

/// ----- FEEDBACK ROUTES -----
Route::name('feedback.')->group(function() {
    Route::get('{userId}/feedback', 'FeedbackController@create')->name('enter');
    Route::get('{feedback}/{studentId}/feedback/', 'FeedbackController@show')->name('view');
    Route::post('feedback/upload', 'FeedbackController@store')->name('upload');
    Route::get('feedback/committee/comments/create/{feedback}', 'DataForProgressCommitteeController@create')->name('committee_data.create');
    Route::post('feedback/committee/comments/store', 'DataForProgressCommitteeController@store')->name('committee_data.store');
    Route::get('feedback/committee/comments/show/{data}', 'DataForProgressCommitteeController@show')->name('committee_data.show');
});

/// ----- DOCUMENT ROUTES -----
Route::resource('document', 'DocumentController', ['only' => [
    'index', 'store', 'show'
]]);

/// ----- SUPERVISOR ROUTES -----
Route::name('supervisor.')->group(function() {
    Route::delete('supervisor/{staff}/{student}', 'SupervisorController@destroy')->name('destroy');
    Route::post('supervisor/', 'SupervisorController@store')->name('store');
});

/// ----- IPAP ROUTES -----
Route::name('ipap.')->group(function() {
    Route::delete('ipap/{staff}/{student}', 'IPAPController@destroy')->name('destroy');
    Route::post('ipap/', 'IPAPController@store')->name('store');
});

Route::resource('meeting', 'IPAPMeetingController', ['only' => [
    'store', 'edit', 'update'
]]);

/// ----- STAFF VIEW ROUTES -----
Route::name('staff_views.')->group(function() {
    Route::get('students/ipap/show', 'StaffViewsController@showIpapStudentsView')->name('students.ipap.show');
    Route::get('students/supervising/show', 'StaffViewsController@showSupervisingStudentsView')->name('students.supervising.show');
});

/// ----- MASQUERADE ROUTES -----
Route::get('masquerade/{username}', 'MasqueradeController@masqueradeAs')->name('masquerade');
Route::get('stop/masquerade', 'MasqueradeController@stopMasquerade')->name('masquerade.stop');

/// ----- EXEMPTION ROUTES -----
Route::get('exemption/{student_username}', 'ExemptionController@request')->name('exemption.request');
Route::get('exemption/grant/{student_username}', 'ExemptionController@grant')->name('exemption.grant');

?>

site/app/Feedback.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Feedback extends Model
{
    protected $connection = 'pgrf';
    protected $table = 'feedback';
    public $timestamps = false;
    protected $guarded = [];

    public function document()
    {
        return $this->belongsTo('App\Document', 'DocumentId');
    }

    public function staff()
    {
        return $this->belongsTo('App\Staff', 'staff_username');
    }

    public function dataForProgressCommittee()
    {
        return $this->hasOne('App\DataForProgressCommittee', 'feedback_id');
    }

    public function grade()
    {
        return $this->hasOne('App\Grade', 'feedback_id');
    }

    public function saveGrade($grade_value)
    {
        $grade = new \App\Grade;
        $grade->value = $grade_value;
        $grade->student()->associate($this->document->student->detail->username);

        $this->grade()->save($grade);
    }

    public function getAnswers(): array
    {
        $answers = Storage::disk('public')->get($this->Location);
        $answers = json_decode($answers, true);
        return array_values($answers);
    }

    public function upload($data)
    {
        $json = json_encode($data);

        $this->Location = $this->getFeedbackFilePath();

        $result = Storage::disk('public')->put($this->Location, $json);
        abort_unless($result, 500, 'Failed to save feedback on server');

    }

    private function getFeedbackFilePath()
    {
        $type_value = snake_case($this->document->type->value);
        $file_name = "fb_{$type_value}_{$this->staff_username}";

        return $this->document->student->username . '/' . $file_name . '.json';
    }
}

site/app/Http/Controllers/FeedbackController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Cookie;

use App\Student;
use App\Staff;
use App\IPAP;
use App\Document;
use App\Feedback;
use App\LUCS_User;
use App\Helpers\FeedbackHelper;

class FeedbackController extends Controller
{
    public function create($docId)
    {
        $document = Document::findOrFail($docId);

        return view('feedback.create', [
            'title' => 'Feedback View',
            'document' => $document,
            'questions' => $document->type->questionnaire->questions->all()
        ]);
    }

    public function show($feedbackId, $studentId)
    {
        $feedback = Feedback::find($feedbackId);

        return view('feedback.view', [
            'title' => 'Feedback View',
            'feedback' => $feedback,
            'document' => $feedback->document,
            'questions' => $feedback->document->type->questionnaire->questions->all(),
            'answers' => $feedback->getAnswers()
        ]);
    }
    
    public function store(Request $request)
    {
        $this->validateRequest($request);

        $document = Document::findOrFail($request->input('docId'));
        
        $feedback = \App\Feedback::make([
            'staff_username' => auth()->user()->username,
            'DocumentId' => $document->id,
        ]);

        $feedback->upload($request->comment);

        $feedback->save();
        event(new \App\Events\FeedbackSubmitted($document->student, $feedback));
        
        if ($document->isEndOfYearReport()) {
            $feedback->saveGrade($request->grade);

            if ($feedback->grade->isUnsatisfactory()) {
                return redirect()->route('feedback.committee_data.create', ['feedback' => $feedback->id]);
            }
        }

        return redirect()->route('home')->with('flashMsg', 'Your feedback was uploaded successfully');
    }

    public function validateRequest(Request $request)
    {
        $rules = ['comment.*' => 'required'];
        $messages = ['required' => 'All fields must contain some feedback'];
        $validator = Validator::make($request->all(), $rules, $messages)->validate();
    }
}

site/resources/views/feedback/create.blade.php
@extends('feedback.index')

@section('feedback.content')
    <form action="{{ URL::route('feedback.upload') }}" method="post">
        @csrf
        @if (str_contains($document->type->value, 'End of Year Report'))
            <div class="form-group">
                <div class="row mt-3">
                    <div class="card" style="width: 100%">
                        <div class="card-body">
                            <h6 for="grade" class="card-title">Grading</h6>
                            <select style="width: 30%" dusk="grade" class="custom-select" id="grade" name="grade" required>
                                @foreach (array('Excellent', 'Good', 'Satisfactory', 'Unsatisfactory') as $key=>$grade)
                                    <option value="{{ $grade }}">{{ $grade }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        @endif
        @foreach ($questions as $question)
            <div class="form-group" id="comment-group{{ $loop->iteration }}">
                <div class="row mt-3">
                    <div class="card" style="width: 100%">
                        <div class="card-body">
                            <label for="comment[{{ $loop->iteration }}]">
                                <h6 class="card-title">{{ $loop->iteration }}. {{ $question->value }}</h6>
                            </label>
                            <textarea dusk="comment{{ $loop->index }}" class="form-control" rows="10" placeholder="Enter feedback..." name="comment[{{ $loop->iteration }}]" required></textarea>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach

        <select class="form-control" name="docId")" hidden>
            <option value="{{ $document->id }}" selected>{{ $document->id }}</option>
        </select>
        <button dusk="submit" type="submit" class="btn btn-success mt-3 mb-3 float-right">Submit</button>
    </form>
@endsection

site/resources/views/feedback/index.blade.php
@extends('layouts.app')

@section('title')
    {{ $document->student->lucsUser->firstnames ?? $document->student->username }} {{ $document->student->lucsUser->surname ?? '' }} - {{ $document->type->value ?? 'Unknown Document Type' }} Feedback
@endsection

@section('content')
    <div class="row mt-3">
        @component('components.alert')
            @slot('print_errors')
                {{ $errors->first() }}
            @endslot
        @endcomponent
    </div>

    <div class="row mt-3">
        <div class="col-md-10">
            @component('components.welcome-msg')
                @slot('msg')
                    {{ $document->student->lucsUser->firstnames ?? $document->student->username }} {{ $document->student->lucsUser->surname ?? '' }} - {{ $document->type->value ?? 'Unknown Document Type' }} Feedback
                @endslot
            @endcomponent
        </div>

        <div class="col-md-2">
            <a class="btn btn-info" href="{{ URL::route('document.show', ['id' => $document->id]) }}">View Document</a>
        </div>
    </div>

    <div class="row-sm mt-3 mb-3">
        <div class="col-sm">
            @yield('feedback.content')
        </div>
    </div>
@endsection

site/resources/views/feedback/view.blade.php
@extends('feedback.index')

@section('feedback.content')
    @if (str_contains($feedback->document->type->value, 'End of Year Report'))
        <div class="form-group">
            <div class="row mt-3">
                <div class="card" style="width: 100%">
                    <div class="card-body">
                        Grading: {{ $feedback->grade->value }}
                    </div>
                </div>
            </div>
        </div>
    @endif

    @foreach ($questions as $question)
        <div class="row mt-3">
            <div class="card" style="width: 100%" id="comment-group{{ $loop->iteration }}">
                <div class="card-body">
                    <h6 class="card-title">{{ $loop->iteration }}. {{ $question->value }}</h6>
                    <hr>
                    <p class="card-text">{{ $answers[$loop->index] }}</p>
                </div>
            </div>
        </div>
    @endforeach

    @if($feedback->grade->value == "Unsatisfactory" && $feedback->document->isEndOfYearReport())
        @unless(auth()->user()->isStudent())
            <a href="{{ URL::route('feedback.committee_data.show', ['data' => $feedback->dataForProgressCommittee->id]) }}" type="button" class="btn btn-info mt-3">View Comments for Progress Committee</a>
        @endunless
    @endif
@endsection