site/routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Http\FileHelpers;
use Illuminate\Filesystem\Filesystem;

/// ----- AUTH ROUTES -----
Route::get('login/', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('login/success', 'Auth\LoginController@login')->name('login.success');

/// ----- HOME ROUTES -----
Route::redirect('/', 'login');
Route::get('/home', 'HomeController@show')->name('home');
/*      ->middleware('lucs.login')->name('home'); */
Route::redirect('intrahome', 'http://intranet.csc.liv.ac.uk' )->name('intrahome');

/// ----- USER ROUTES -----
Route::resource('user', 'UserController', ['only' => [
    'index'
]]);

/// ----- STUDENT ROUTES -----
Route::resource('student', 'StudentController', ['except' => [
    'destroy'
]])->middleware('lucs.login');
Route::post('student/bulk', 'StudentController@storeBulk')->name('student.bulk.store');
Route::get('student/bulk/create', 'StudentController@createBulk')->name('student.bulk.create');

/// ----- PHD PLAN ROUTES -----
Route::resource('plan/approval', 'PhdPlanApprovalController', ['only' => [
    'create', 'store'
]]);

/// ----- WORKFLOW ROUTES -----
Route::get('workflow/create/{student}', 'WorkflowController@create')->name('workflow.create');
Route::resource('workflow', 'WorkflowController', ['only' => [
    'store', 'update', 'destroy'
]]);

/// ----- WORKFLOW TYPE ROUTES -----
Route::resource('workflow_type', 'WorkflowTypeController', [ 'only' => [
    'show'
]]);

/// ----- FEEDBACK ROUTES -----
Route::name('feedback.')->group(function() {
    Route::get('{userId}/feedback', 'FeedbackController@create')->name('enter');
    Route::get('{feedback}/{studentId}/feedback/', 'FeedbackController@show')->name('view');
    Route::post('feedback/upload', 'FeedbackController@store')->name('upload');
    Route::get('feedback/committee/comments/create/{feedback}', 'DataForProgressCommitteeController@create')->name('committee_data.create');
    Route::post('feedback/committee/comments/store', 'DataForProgressCommitteeController@store')->name('committee_data.store');
    Route::get('feedback/committee/comments/show/{data}', 'DataForProgressCommitteeController@show')->name('committee_data.show');
});

/// ----- DOCUMENT ROUTES -----
Route::resource('document', 'DocumentController', ['only' => [
    'index', 'store', 'show'
]]);

/// ----- SUPERVISOR ROUTES -----
Route::name('supervisor.')->group(function() {
    Route::delete('supervisor/{staff}/{student}', 'SupervisorController@destroy')->name('destroy');
    Route::post('supervisor/', 'SupervisorController@store')->name('store');
});

/// ----- IPAP ROUTES -----
Route::name('ipap.')->group(function() {
    Route::delete('ipap/{staff}/{student}', 'IPAPController@destroy')->name('destroy');
    Route::post('ipap/', 'IPAPController@store')->name('store');
});

Route::resource('meeting', 'IPAPMeetingController', ['only' => [
    'store', 'edit', 'update'
]]);

/// ----- STAFF VIEW ROUTES -----
Route::name('staff_views.')->group(function() {
    Route::get('students/ipap/show', 'StaffViewsController@showIpapStudentsView')->name('students.ipap.show');
    Route::get('students/supervising/show', 'StaffViewsController@showSupervisingStudentsView')->name('students.supervising.show');
});

/// ----- MASQUERADE ROUTES -----
Route::get('masquerade/{username}', 'MasqueradeController@masqueradeAs')->name('masquerade');
Route::get('stop/masquerade', 'MasqueradeController@stopMasquerade')->name('masquerade.stop');

/// ----- EXEMPTION ROUTES -----
Route::get('exemption/{student_username}', 'ExemptionController@request')->name('exemption.request');
Route::get('exemption/grant/{student_username}', 'ExemptionController@grant')->name('exemption.grant');

?>

site/app/Http/Controllers/WorkflowTypeController.php
<?php

namespace App\Http\Controllers;

use App\WorkflowType;
use Illuminate\Http\Request;

class WorkflowTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\WorkflowType  $workflowType
     * @return \Illuminate\Http\Response
     */
    public function show(WorkflowType $workflowType)
    {
        return view('workflow_types.phd_plan.show', [
            'workflow_type' => $workflowType
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\WorkflowType  $workflowType
     * @return \Illuminate\Http\Response
     */
    public function edit(WorkflowType $workflowType)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\WorkflowType  $workflowType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, WorkflowType $workflowType)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\WorkflowType  $workflowType
     * @return \Illuminate\Http\Response
     */
    public function destroy(WorkflowType $workflowType)
    {
        //
    }
}

site/resources/views/workflow_types/phd_plan/show.blade.php
@extends('layouts.app')

@section('title')
    {{ $workflow_type->value ?? 'Unknown Workflow Type' }} - Overview
@endsection

@section('content')
    <div class="row-sm mt-3">
        <div class="row">
            <h4>
                <span style="text-align: left">
                    {{ $workflow_type->value ?? 'Unknown Workflow Type' }} - Overview
                </span>
            </h4>
        </div>
        <div class="mt-3 mb-3">
            {{ $workflows = \App\Workflow::where('workflow_type_id', '=', $workflow_type->id)->paginate(50) }}
            <table class="display table table-responsive-sm table-hover" id="workflow_type-overview-table" dusk="workflow_type-overview-table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">Year of Study</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach ($workflows as $workflow)
                        <tr name="{{ $workflow->student->username }}" class="@if (\App\Helpers\StatusColorHelper::shouldWarn($workflow->status)) bg-warning @endif">
                            <td><a href="{{ URL::route('student.show', ['id' => $workflow->student->username]) }}">{{ $workflow->student->lucsUser->firstnames ?? $workflow->student->username }} {{ $workflow->student->lucsUser->surname ?? '' }}</a></td>
                            <td>{{ date_format(date_create($workflow->student->detail->StartDate), 'jS M Y') ?? 'Unknown' }}</td>
                            <td align="center">{{ $workflow->student->detail->YearOfStudy ?? 'Unknown' }}</td>
                            <td align="center">{{ $workflow->status->name ?? 'Unknown' }}</td>
                        </tr>
                    @endforeach

                </tbody>
            </table>
            {{ $workflows->links() }}
        </div>
    </div>

    <script>
     $(document).ready(function() {
         $('#workflow_type-overview-table').DataTable( {
             "order": [[ 2, "asc" ], [0, 'asc']]
         } );
     } );
    </script>
@endsection