site/routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Http\FileHelpers;
use Illuminate\Filesystem\Filesystem;

/// ----- AUTH ROUTES -----
Route::get('login/', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('login/success', 'Auth\LoginController@login')->name('login.success');

/// ----- HOME ROUTES -----
Route::redirect('/', 'login');
Route::get('/home', 'HomeController@show')->name('home');
/*      ->middleware('lucs.login')->name('home'); */
Route::redirect('intrahome', 'http://intranet.csc.liv.ac.uk' )->name('intrahome');

/// ----- USER ROUTES -----
Route::resource('user', 'UserController', ['only' => [
    'index'
]]);

/// ----- STUDENT ROUTES -----
Route::resource('student', 'StudentController', ['except' => [
    'destroy'
]])->middleware('lucs.login');
Route::post('student/bulk', 'StudentController@storeBulk')->name('student.bulk.store');
Route::get('student/bulk/create', 'StudentController@createBulk')->name('student.bulk.create');

/// ----- PHD PLAN ROUTES -----
Route::resource('plan/approval', 'PhdPlanApprovalController', ['only' => [
    'create', 'store'
]]);

/// ----- WORKFLOW ROUTES -----
Route::get('workflow/create/{student}', 'WorkflowController@create')->name('workflow.create');
Route::resource('workflow', 'WorkflowController', ['only' => [
    'store', 'update', 'destroy'
]]);

/// ----- WORKFLOW TYPE ROUTES -----
Route::resource('workflow_type', 'WorkflowTypeController', [ 'only' => [
    'show'
]]);

/// ----- FEEDBACK ROUTES -----
Route::name('feedback.')->group(function() {
    Route::get('{userId}/feedback', 'FeedbackController@create')->name('enter');
    Route::get('{feedback}/{studentId}/feedback/', 'FeedbackController@show')->name('view');
    Route::post('feedback/upload', 'FeedbackController@store')->name('upload');
    Route::get('feedback/committee/comments/create/{feedback}', 'DataForProgressCommitteeController@create')->name('committee_data.create');
    Route::post('feedback/committee/comments/store', 'DataForProgressCommitteeController@store')->name('committee_data.store');
    Route::get('feedback/committee/comments/show/{data}', 'DataForProgressCommitteeController@show')->name('committee_data.show');
});

/// ----- DOCUMENT ROUTES -----
Route::resource('document', 'DocumentController', ['only' => [
    'index', 'store', 'show'
]]);

/// ----- SUPERVISOR ROUTES -----
Route::name('supervisor.')->group(function() {
    Route::delete('supervisor/{staff}/{student}', 'SupervisorController@destroy')->name('destroy');
    Route::post('supervisor/', 'SupervisorController@store')->name('store');
});

/// ----- IPAP ROUTES -----
Route::name('ipap.')->group(function() {
    Route::delete('ipap/{staff}/{student}', 'IPAPController@destroy')->name('destroy');
    Route::post('ipap/', 'IPAPController@store')->name('store');
});

Route::resource('meeting', 'IPAPMeetingController', ['only' => [
    'store', 'edit', 'update'
]]);

/// ----- STAFF VIEW ROUTES -----
Route::name('staff_views.')->group(function() {
    Route::get('students/ipap/show', 'StaffViewsController@showIpapStudentsView')->name('students.ipap.show');
    Route::get('students/supervising/show', 'StaffViewsController@showSupervisingStudentsView')->name('students.supervising.show');
});

/// ----- MASQUERADE ROUTES -----
Route::get('masquerade/{username}', 'MasqueradeController@masqueradeAs')->name('masquerade');
Route::get('stop/masquerade', 'MasqueradeController@stopMasquerade')->name('masquerade.stop');

/// ----- EXEMPTION ROUTES -----
Route::get('exemption/{student_username}', 'ExemptionController@request')->name('exemption.request');
Route::get('exemption/grant/{student_username}', 'ExemptionController@grant')->name('exemption.grant');

?>

site/app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Student extends Model
{
    use Notifiable;

    public $timestamps = false;
    public $incrementing = false;

    protected $table = 'staff';
    protected $primaryKey = 'username';
    protected $keyType = 'string';
    protected $guarded = [];

    protected $attributes = [
        'status' => 'phd',
        'office' => NULL
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new \App\Scopes\StudentScope);
    }
    
    public function lucsUser()
    {
        return $this->belongsTo('App\LUCS_User', 'username');
    }

    public function detail()
    {
        return $this->hasOne('App\StudentDetail', 'username');
    }
    
    public function ipaps()
    {
        return $this->belongsToMany('App\Staff', 'ipap', 'student_username', 'staff_username');
    }

    public function supervisors()
    {
        return $this->belongsToMany('App\Staff', 'supervisor', 'student_username', 'staff_username');
    }

    public function documents()
    {
        return $this->hasMany('App\Document', 'student_username');
    }

    public function workflows()
    {
        return $this->hasMany('App\Workflow', 'student_username');
    }

    public function canUpload(\App\WorkflowType $type): bool
    {
        if ($this->detail->YearOfStudy > 1 && $type->value == 'PhD Plan')
        {
            return false;
        }

        return true;
    }

    public function createNewStarterStudentDetail($start_date, \App\Department $department, bool $is_xjtlu = false, bool $is_part_time = false)
    {
        $detail = new \App\StudentDetail;
        $detail->StartDate = $start_date;
        $detail->YearOfStudy = 1;
        $detail->status_id = 1;
        $detail->department()->associate($department);
        $detail->is_xjtlu = $is_xjtlu;
        $detail->is_part_time = $is_part_time;

        $this->detail()->save($detail);
    }

    /**
     * Route notifications for the mail channel.
     *
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return string
     */
    public function routeNotificationForMail($notification)
    {
        return $this->lucsUser->email;
    }
}

site/app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Carbon;

use App\Student;

/* use Illuminate\Foundation\Bus\DispatchesJobs;
 * use Illuminate\Routing\Controller as BaseController;
 * use Illuminate\Foundation\Validation\ValidatesRequests;
 * use Illuminate\Foundation\Auth\Access\AuthorizesRequests;*/

class StudentController extends Controller
{
    public function index()
    {
        return view('student.index');
    }

    public function show($id)
    {
        abort_unless(auth()->user()->can('view', \App\Student::find($id)), 403, 'Not authenticated');

        $student = \App\LUCS_User::findOrFail($id);

        abort_unless($student->student->status === 'phd', 404);

        return view('student.show', [
            'student' => $student,
        ]);
    }

    public function create()
    {
        abort_unless(auth()->user()->can('create', \App\Student::class), 403, 'Not authenticated');

        return view('student.create');
    }

    public function store(Request $request)
    {
        $this->validateStoreRequest($request);
        
        $user = new \App\LUCS_User;
        $user->username = $request->username;
        $user->firstnames = $request->firstName;
        $user->surname = $request->lastName;
        $user->email = $request->email . '@liverpool.ac.uk';
        $user->save();

        $user->student()->save(\App\Student::make());

        $user->student->createNewStarterStudentDetail(
            $request->startDate,
            \App\Department::findOrFail($request->department),
            $request->has('is-xjtlu'),
            $request->has('is-part-time')
        );

        if ($request->has('ipaps')) {
            foreach ($request->ipaps as $username) {
                if (strcmp($username, 'null') == 0) { continue; }

                $user->student->ipaps()->attach($username);
            }
        }

        if ($request->has('supervisors')) {
            foreach ($request->supervisors as $username) {
                if (strcmp($username, 'null') == 0) { continue; }
                
                $user->student->supervisors()->attach($username);
            }
        }

        return redirect()->route('student.show', ['id' => $user->username])->with('flashMsg', 'A new student was added successfully');
    }

    public function createBulk()
    {
        abort_unless(auth()->user()->isAdmin(), 403);

        return view('student.create_bulk');
    }

    public function storeBulk(Request $request)
    {
        abort_unless(auth()->user()->isAdmin(), 403);

        $rules = ['student-data' => 'required|mimes:csv,plain'];
        $messages = ['student-data.mimes' => 'The uploaded file must be in CSV format'];

        Validator::make($request->all(), $rules, $messages);

        $csv = $this->csvDataToArray($request->file('student-data'));
        
        foreach ($csv as $data) {
            $user = \App\LUCS_User::make([
                'username' => $data['username'] ?? '',
                'firstnames' => $data['firstnames'] ?? NULL,
                'surname' => $data['surname'] ?? NULL,
                'email' => $data['email'] ?? NULL

            ] ?? NULL);

            $user->student()->save(\App\Student::make());
            $user->student->createNewStarterStudentDetail(
                $data['start-date'] ?? NULL,
                \App\Department::where('value', 'LIKE', $data['department'] ?? '')->first(),
                $data['is-xjtlu'] ?? false,
                $data['is-part-time'] ?? false
            );

            $user->save();
        }

        return redirect()->route('home')->with('flashMsg', 'The students have been created successfully');
        }

    public function edit($id)
    {
        abort_unless(auth()->user()->can('update', \App\Student::find($id)), 403, 'Not authenticated');

        $student = \App\Student::findOrFail($id);

        return view('student.edit', ['student' => $student]);
    }

    public function update(Request $request, $id)
    {
        $this->validateUpdateRequest($request);

        $student = \App\Student::findOrFail($id);

        abort_unless(auth()->user()->can('update', $student), 403, 'Only admins may update student data');

        $student->lucsUser->update([
            'firstnames' => $request->firstName,
            'surname' => $request->lastName,
            'email' => $request->email . '@liverpool.ac.uk',
        ]);

        $student->detail->update([
            'StartDate' => date('Y-m-d', strtotime($request->startDate)),
            'YearOfStudy' => $request->yearOfStudy
        ]);

        return redirect()->route('student.show', ['id' => $student->username])->with('flashMsg', 'Student details updated successfully');
    }

    private function validateStoreRequest(Request $request)
    {
        abort_unless(auth()->user()->can('create', \App\Student::class), 403, 'Not authenticated');

        $rules = [
            'firstName' => 'alpha',
            'lastName' => 'alpha',
            'username' => 'alpha_num',
            'email' => 'alpha_dash|unique:people,email',
            'startDate' => 'date',
            'supervisors.*' => 'nullable',
            'ipaps.*' => 'nullable',
            'is-xjtlu' => 'nullable',
            'is-part-time' => 'nullable'
        ];

        $messages = [
            'firstName.alpha' => "The student's first name must be entirely alphabetical characters",
            'lastName.alpha' => "The student's last name must be entirely alphabetical characters",
            'email.alpha_dash' => 'The email address can contain only letters, numbers, dashes and underscores',
            'ipaps.distinct' => 'The selected IPAP Members must be different',
            'supervisors.distinct' => 'The selected Supervisors must be different'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        $validator->validate();
    }

    private function validateUpdateRequest(Request $request)
    {
        $rules = [
            'firstName' => 'alpha',
            'lastName' => 'alpha',
            'email' => 'unique:people,email',
        ];

        $messages = [
            'firstName.alpha' => "The student's first name must be entirely alphabetical characters",
            'lastName.alpha' => "The student's last name must be entirely alphabetical characters",
            'email.alpha_dash' => 'The email address can contain only letters, numbers, dashes and underscores',
        ];

        Validator::make($request->all(), $rules, $messages)->validate();

    }

    private function csvDataToArray($csv_file): array
    {
        $csv = array_map('str_getcsv', file($csv_file));

        array_walk($csv, function(&$a) use ($csv) {
            $a = array_combine($csv[0], $a);
        });
        array_shift($csv); # remove column header

        return $csv;
    }
}

site/resources/views/student/create.blade.php
@extends('layouts.app')

@section('title')
    New Student
@endsection

@section('content')
    <div class="row-sm mt-3">
        @component('components.welcome-msg')
            @slot('msg')
                <h4 class="mb-3">
                    <span style="text-align:left;">
                        Create New Student 
                    </span>
                    <span style="float:right;">
                        <a class="btn btn-info" href="{{ URL::route('student.bulk.create') }}">Bulk Create</a>
                    </span>
                </h4>
            @endslot
        @endcomponent
    </div>
    <div class="row-sm mt-3">
        <div class="col-sm">
            @component('components.alert')
                @slot('print_errors')
                    @foreach ($errors->all() as $error)
                        {{ $error }}
                        @unless($loop->last)
                    <hr/>
                        @endunless
                    @endforeach
                @endslot
            @endcomponent

            <form action="{{ URL::route('student.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="names">Student Name</label>
                    <div id="names" class="form-row">
                        <div class="col-sm">
                            <input type="text" dusk="firstname" name="firstName" class="form-control" placeholder="Full name" required>
                        </div>
                        <div class="col-sm">
                            <input type="text" dusk="surname" name="lastName" class="form-control" placeholder="Last name" required>
                        </div>
                    </div>
                </div>

                <div class="form-group mt-3">
                    <div class="form-row">
                        <div class="col-sm">
                            <label for="email">Username</label>
                            <div class="input-group">
                                <input id="username" dusk="username" name="username" type="text" class="form-control" placeholder="Username" required/>
                            </div>
                        </div>
                        <div class="col-sm">
                            <label for="email">Email Address</label>
                            <div class="input-group">
                                <input id="email" dusk="email" name="email" type="text" class="form-control" placeholder="Email" required/>
                                <div class="input-group-append"><span class="input-group-text">{{ '@liverpool.ac.uk' }}</span></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group mt-3">
                    <div class="form-row">
                        <div class="col-sm-3">
                            <label for="startDate">Start Date</label>
                            <input dusk="start-date" id="startDate" name="startDate" class="form-control" type="date" required/>
                        </div>
                        <div class="col-sm-3 ml-4">
                            <label for="department">Department</label>
                            <select name="department" id="department" class="custom-select" dusk="department" required>
                                @foreach (\App\Department::all() as $department)
                                    <option value="{{ $department->id }}">{{ $department->value }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-sm-2 mt-5 ml-2">
                            <div class="form-check">
                                <input dusk="is-xjtlu" id="is-xjtlu" name="is-xjtlu" class="form-check-input" type="checkbox"/>
                                <label for="is-xjtlu" class="form-check-label">XJTLU</label>
                            </div>
                        </div>
                        <div class="col-sm-2 mt-5">
                            <div class="form-check">
                                <input dusk="is-part-time" id="is-part-time" name="is-part-time" class="form-check-input" type="checkbox"/>
                                <label for="is-part-time" class="form-check-label">Part Time</label>
                            </div>
                        </div>
                    </div>
                </div>

                <hr/>

                <div class="form-row">
                    @for ($incr = 0; $incr < 2; $incr++)
                        <div class="col-sm">
                            <div class="form-group mt-3">
                                <label for="supervisors[{{ $incr }}]">Supervisor {{ $incr+1 }}</label>
                                <select dusk="supervisors[{{ $incr }}]" class="custom-select" id="supervisors[{{ $incr }}" name="supervisors[{{ $incr }}]" required>
                                    <option value="null" selected>None</option>
                                    @foreach (\App\Staff::all() as $supervisor)
                                        <option value="{{ $supervisor->username }}">{{ $supervisor->lucsUser->getFullNameOrUsername() }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    @endfor
                </div>

                <div class="form-row">
                    @for ($incr = 0; $incr < 2; $incr++)
                        <div class="col-sm">
                            <div class="form-group mt-3">
                                <label for="ipaps[{{ $incr }}]">IPAP Member {{ $incr+1 }}</label>
                                <select dusk="ipaps[{{ $incr }}]" class="custom-select" id="ipaps[{{ $incr }}]" name="ipaps[{{ $incr }}]" required>
                                    <option value="null" selected>None</option>
                                    @foreach (\App\Staff::all() as $ipap)
                                        <option value="{{ $ipap->username }}">{{ $ipap->lucsUser->getFullNameOrUsername() }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    @endfor
                </div>

                <button dusk="submit" type="submit" class="btn btn-success mt-3 mb-3 float-right">Create</button>
            </form>
        </div>
    </div>
@endsection

site/resources/views/student/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Details - {{ $student->lucsUser->firstnames }} {{ $student->lucsUser->surname }}
@endsection

@section('content')
    <div class="row-sm mt-3">
        @component('components.welcome-msg')
        @slot('msg')
        Edit Details - {{ $student->lucsUser->firstnames }} {{ $student->lucsUser->surname }}
        @endslot
        @endcomponent
    </div>
    <div class="row-sm mt-3">
        <div class="col-sm">
            @component('components.alert')
            @slot('print_errors')
            @foreach ($errors->all() as $error)
                {{ $error }}
                @unless($loop->last)
                    <hr/>
                @endunless
            @endforeach
            @endslot
            @endcomponent

            <form action="{{ URL::route('student.update', ['id' => $student->username]) }}" method="post">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="names">Student Name</label>
                    <div id="names" class="row">
                        <div class="col-sm-5">
                            <input type="text" name="firstName" class="form-control" value="{{ $student->lucsUser->firstnames }}" placeholder="First name" required/>
                        </div>
                        <div class="col-sm-5">
                            <input type="text" name="lastName" class="form-control" value="{{ $student->lucsUser->surname }}" placeholder="Last name" required/>
                        </div>
                    </div>
                </div>

                <div class="form-group mt-3">
                    <div class="row">
                        <div class="col-sm-5">
                            <label for="email">Email Address</label>
                            <div class="input-group">
                                <input id="email" name="email" type="text" class="form-control" value="{{ str_before($student->lucsUser->email, '@') }}" placeholder="Username" required/>
                                <div class="input-group-append"><span class="input-group-text">{{ '@liverpool.ac.uk' }}</span></div>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <label for="startDate">Start Date</label>
                            <input id="startDate" name="startDate" class="form-control" value="{{ $student->detail->StartDate }}" type="date" required/>
                        </div>

                        <div class="col-sm-2">
                            <label for="yearOfStudy">Year of Study</label>
                            <input class="form-control" id="yearOfStudy" name="yearOfStudy" type="number" value="{{ $student->detail->YearOfStudy }}" min="1" max="4" required/>
                        </div>
                    </div>
                </div>

                <div class="form-group mt-3">
                    <div class="form-row">
                        <div class="col-sm-3">
                            <div class="form-check">
                                <input dusk="is-xjtlu" id="is-xjtlu" name="is-xjtlu" class="form-check-input" type="checkbox" {{ $student->detail->is_xjtlu ? 'checked' : ''}}/>
                                <label for="is-xjtlu" class="form-check-label">XJTLU</label>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-check">
                                <input dusk="is-part-time" id="is-part-time" name="is-part-time" class="form-check-input" type="checkbox" {{ $student->detail->is_part_time ? 'checked' : ''}}/>
                                <label for="is-part-time" class="form-check-label">Part Time</label>
                            </div>
                        </div>
                    </div>
                </div>

                <hr/>
                <a href="{{ URL::route('student.show', ['id' => $student->username]) }}" dusk="cancel" class="btn btn-secondary float-left">Cancel</a>
                <button type="submit" dusk="submit" class="btn btn-success mt-3 mb-3 float-right">Submit</button>
            </form>
        </div>
    </div>
@endsection

site/resources/views/student/index.blade.php
@extends('layouts.app')

@section('title')
    All Students
@endsection

@section('content')
    @component('components.student-list', ['students' => \App\Student::all(), 'id' => 1])
    @endcomponent
@endsection

site/resources/views/student/show.blade.php
@extends('layouts.app')

@section('title')
    {{ $student->firstnames }} {{ $student->surname }} - Details
@endsection

@section('profile')
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <span style="text-align:left;">
                    {{ $student->firstnames ?? $student->username }} {{ $student->surname ?? '' }} 
                </span>
                <span style="float: right;">
                    <a href="{{ URL::route('student.edit', ['id' => $student->username]) }}">
                        <i class="fas fa-pen-square text-primary"></i>
                    </a>
                </span>
            </h4>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Email:
                <a href="mailto:{{ $student->email ?? '' }}">{{ $student->email ?? 'Unknown' }}</a>
            </li>
            <li class="list-group-item">Department: {{ $student->student->detail->department->value ?? 'Unknown' }}</li>
            <li class="list-group-item">Start Date: {{ date_format(date_create($student->student->detail->StartDate), 'jS M Y') ?? 'Unknown' }}</li>
            <li class="list-group-item">Study Year: {{ $student->student->detail->YearOfStudy ?? 'Unknown' }}</li>
            @if ($student->student->detail->is_xjtlu ?? false)
                <li class="list-group-item">XJTLU</li>
            @endif
            @if ($student->student->detail->is_part_time ?? false)
                <li class="list-group-item">Part Time</li>
            @endif
        </ul>
    </div>
@endsection

@section('workflows')
    <h4>
        <span style="text-align: left;">Workflows</span>
        @if (auth()->user()->isAdmin())
            <span style="float: right;">
                <a class="btn btn-sm btn-success" type="button" href="{{ URL::route('workflow.create', ['student' => $student->username]) }}">Add</a>
            </span>
        @endif
    </h4>
    @forelse ($student->student->workflows as $workflow)
        <div class="mb-3">
            @component('components.workflows.show', ['workflow' => $workflow])
            @endcomponent
        </div>
    @empty
            <div class="card">
                <div class="card-body text-center">
                    <p>No workflows exist</p>
                </div>
            </div>
    @endforelse
@endsection

@section('submitted-documents')
    <h4>Submitted Documents</h4>
    @forelse($student->student->documents as $document)
        @component('components.document', ['doc' => $document])
        @endcomponent
    @empty
        <div class="card mt-3">
            <div class="card-body">
                <p class="card-title">No documents have been submitted yet</p>
            </div>
        </div>
    @endforelse
@endsection

@section('supervisors')
    @component('components.staff-list', ['student' => $student->student, 'staffMembers' => $student->student->supervisors, 'route' => 'supervisor.destroy'])
        @slot('subTitle')
            <span style="text-align: left;">Supervisors</span>
            @if (auth()->user()->isAdmin())
                <span style="float: right;">
                    <button class="btn btn-sm btn-success" type="button" data-toggle="modal" data-target="#add-staff-supervisor" dusk="add-supervisor">Add</button>
                </span>
            @endif
        @endslot

        @slot('relationship')
            supervisor
        @endslot
    @endcomponent
@endsection

@section('ipaps')
    @component('components.staff-list', ['student' => $student->student, 'staffMembers' => $student->student->ipaps, 'route' => 'ipap.destroy'])
        @slot('subTitle')
            <span style="text-align: left;">IPAP Members</span>

            @if (auth()->user()->isAdmin())
                <span style="float: right;">
                    <button class="btn btn-sm btn-success" type="button" data-toggle="modal" data-target="#add-staff-ipap" dusk="add-ipap">Add</button>
                </span>
            @endif
        @endslot

        @slot('relationship')
            ipap
        @endslot
    @endcomponent
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-4 mt-3">
            @yield('profile')
        </div>

        <div class="col-sm-8 mt-3">
            <div class="mb-5">
                @yield('workflows')
                <hr/>
            </div>

            <div class="mb-5">
                @yield('submitted-documents')
                <hr/>
            </div>

            <div class="mb-3">
                @yield('supervisors')
            </div>

            @yield('ipaps')
        </div>
    </div>

    <div class="modal fade" id="confirm-exemption" tabindex="-1" role="dialog" aria-labelledby="confirm-exemption" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Only request an exemption if the student has completed more than 50% of the write up of
                    their thesis.
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal" type="button">Cancel</button>
                    <a type="button" class="btn btn-danger" href="{{ route('exemption.request', ['username' => $student->username]) }}" dusk="confirm-exemption">Request Exemption</a>
                </div>
            </div>
        </div>
    </div>

    @if(auth()->user()->isAdmin())
        @component('components.supervisor_ipap.create', ['student' => $student->student, 'url' => URL::route('supervisor.store')])
            @slot('relationship')
                supervisor
            @endslot

            @slot('options')
                @foreach(\App\LUCS_User::staffMembers()->orderBy('surname', 'asc')->get() as $supervisor)
                    <option value="{{ $supervisor->username }}">{{ $supervisor->firstnames }}  {{ $supervisor->surname }}</option>
                @endforeach
            @endslot
        @endcomponent
    @endif

    @if(auth()->user()->isAdmin())
        @component('components.supervisor_ipap.create', ['student' => $student->student, 'url' => URL::route('ipap.store')])
            @slot('relationship')
                IPAP
            @endslot

            @slot('options')
                @foreach(\App\LUCS_User::staffMembers()->orderBy('surname', 'asc')->get() as $ipap)
                    <option value="{{ $ipap->username }}">{{ $ipap->firstnames }}  {{ $ipap->surname }}</option>
                @endforeach
            @endslot
        @endcomponent
    @endif
@endsection